url: http://www.optimizations.ml
sourceurl: //www.optimizations.ml
baseurl: 
title: OPTIMIZATIONS for Machine Learning
subtitle: Optimization Methods for Machine Learning
logo: badge_op_ml.png
author: QU Xiaofeng
email: xiaofeng.qu.hk@ieee.org
simple_search: http://bing.com/search
description: A little blog collecting optimization methods in machine learning field
name: OPTIMIZATIONS.ML
markdown: Kramdown
kramdown:
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: pretty
timezone: Asia/Hong_Kong
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['.gitignore','UploadToGithub.Rakefile','LICENSE','Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
data:
  options:
    mathjax: true
    katex: true
  social:
    - link: //www.twitter.com/quxiaofeng
      icon: icon-twitter
    - link: //www.facebook.com/quxiaofeng
      icon: icon-facebook
    - link: //github.com/quxiaofeng
      icon: icon-github
    - link: //www.quxiaofeng.me/optimization/feed
      icon: icon-feed
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: subl
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: 
