url: http://www.optimizations.ml
baseurl:
title: OPTIMIZATIONS.ML
subtitle: Optimization Methods for Machine Learning
logo: badge_op_ml.png
author: QU Xiaofeng
email: xiaofeng.qu.hk@ieee.org
simple_search: http://google.com/search
description: A little blog collecting optimization methods in machine learning field
name: OPTIMIZATIONS.ML
markdown: Kramdown
kramdown:
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: pretty
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/